// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsrWbFzblzwPxbzh-zR8bxuQ8VmC9dX7w',
    appId: '1:850554461811:web:3728e7a7b4ffd9783c9406',
    messagingSenderId: '850554461811',
    projectId: 'chatapp-b10cb',
    authDomain: 'chatapp-b10cb.firebaseapp.com',
    storageBucket: 'chatapp-b10cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI9eizbUFdMuOEBkxYskDTSKRddFX3rrE',
    appId: '1:850554461811:android:89a8f3e72c2a55383c9406',
    messagingSenderId: '850554461811',
    projectId: 'chatapp-b10cb',
    storageBucket: 'chatapp-b10cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKhtG3WJFDNBv4FGGElo5w2fTzN-QO0s',
    appId: '1:850554461811:ios:baabaa8b94c8183d3c9406',
    messagingSenderId: '850554461811',
    projectId: 'chatapp-b10cb',
    storageBucket: 'chatapp-b10cb.firebasestorage.app',
    iosBundleId: 'com.example.myntraHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKhtG3WJFDNBv4FGGElo5w2fTzN-QO0s',
    appId: '1:850554461811:ios:baabaa8b94c8183d3c9406',
    messagingSenderId: '850554461811',
    projectId: 'chatapp-b10cb',
    storageBucket: 'chatapp-b10cb.firebasestorage.app',
    iosBundleId: 'com.example.myntraHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsrWbFzblzwPxbzh-zR8bxuQ8VmC9dX7w',
    appId: '1:850554461811:web:a0c1f17c2b8398703c9406',
    messagingSenderId: '850554461811',
    projectId: 'chatapp-b10cb',
    authDomain: 'chatapp-b10cb.firebaseapp.com',
    storageBucket: 'chatapp-b10cb.firebasestorage.app',
  );
}
